[package]
name = "deb-control"
description = "Crate for DEB/control file generation"
version = "0.2.0"
authors = ["wojciechkepka <wojciech@wkepka.dev>"]
edition = "2018"
license = "MIT"

[dependencies]
paste = "1"
pkgspec = { git = "https://github.com/wojciechkepka/pkgspec", branch = "master" }
